version: '3.3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - '10125:8080'
      - '9443:8443'
      - '50000:50000'
    privileged: true
    volumes:
      - '$PWD/jenkins_home:/jenkins_config'
    networks:
      - net
volumes:
  jenkins_home:
    driver: local
networks:
  net:
