apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  labels:
    app: wordpress-mysql
type: Opaque
data:
  password: RGVtbzEyMzQ1IQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  labels:
    app: wordpress-web
type: Opaque
data:
  password: RGVtbzEyMzQ1IQo=